-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 09:51:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT 'Id - PK e AI.',
  `Nome` VARCHAR(45) NOT NULL COMMENT 'Nome Cliente',
  `CPF_CNPJ` BIGINT(14) NOT NULL COMMENT 'CPF - CNPJ - controle de tipo 11 ou 14 caractes via App.\nMaximo digitos 14.',
  `Endereço` VARCHAR(80) NULL,
  `Tipo_Pessoa` TINYINT NOT NULL DEFAULT 1 COMMENT 'Tipo pessoa - 0-PF/1-PJ',
  `Ativo` TINYINT NOT NULL DEFAULT 1 COMMENT 'Status - 1-Ativo/0-Inativo',
  `Obs` VARCHAR(80) NULL COMMENT 'Obs- campo texto livre',
  `Aniversátio` DATE NOT NULL COMMENT 'Data aniversário',
  `Inclusao` DATE NOT NULL COMMENT 'Data inclusão',
  PRIMARY KEY (`idCliente`, `CPF_CNPJ`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCliente_UNIQUE` ON `mydb`.`Cliente` (`idCliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CPF-CNPJ_UNIQUE` ON `mydb`.`Cliente` (`CPF_CNPJ` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT COMMENT 'Numer pedido',
  `Cliente_idCliente` INT NOT NULL COMMENT 'ID Cliente',
  `Ativo` TINYINT NOT NULL COMMENT 'Status - 1-Ativo/2-Finalizado/3-Cancelado/4-Devoluçao/5-Em Entrega',
  `Descrição` VARCHAR(45) NULL COMMENT 'Descricao - obs',
  `Frete` FLOAT NOT NULL COMMENT 'Frete valor',
  `LocalEntrega` VARCHAR(45) NOT NULL COMMENT 'Local entrega',
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`),
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPedido_UNIQUE` ON `mydb`.`Pedido` (`idPedido` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT COMMENT 'ID - codigo produto',
  `Nome` VARCHAR(45) NOT NULL COMMENT 'Nome - descriçlão ',
  `Categoria` VARCHAR(45) NOT NULL DEFAULT 0 COMMENT 'Categoria - tipo produto',
  `Valor` FLOAT NOT NULL COMMENT 'Valor ',
  `Nota` FLOAT NULL DEFAULT 0 COMMENT 'Nota produto',
  `Peso` FLOAT NOT NULL DEFAULT 0 COMMENT 'Pseo produto',
  `Volume` FLOAT NOT NULL DEFAULT 0 COMMENT 'Volume produto',
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idProduto_UNIQUE` ON `mydb`.`Produto` (`idProduto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Fornecedor ',
  `Nome` VARCHAR(45) NOT NULL COMMENT 'Nome fornecedor',
  `CNPJ` BIGINT(14) NOT NULL COMMENT 'CNPJ ',
  `Contato` VARCHAR(45) NOT NULL COMMENT 'Contato',
  `Endereço` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CNPJ_UNIQUE` ON `mydb`.`Fornecedor` (`CNPJ` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto_has_Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_Fornecedor` (
  `Produto_idProduto` INT NOT NULL COMMENT 'ID Produto',
  `Fornecedor_idFornecedor` INT NOT NULL COMMENT 'Id FOrnecedor ',
  PRIMARY KEY (`Produto_idProduto`, `Fornecedor_idFornecedor`),
  CONSTRAINT `fk_Produto_has_Fornecedor_Produto`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Estoque ',
  `Local` VARCHAR(45) NULL COMMENT 'Local ',
  `Qtde` INT NULL DEFAULT 0 COMMENT 'Qtde estoque',
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idEstoque_UNIQUE` ON `mydb`.`Estoque` (`idEstoque` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto_has_Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_Estoque` (
  `Produto_idProduto` INT NOT NULL COMMENT 'ID Produto',
  `Estoque_idEstoque` INT NOT NULL COMMENT 'Id Estoque',
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pedido_has_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido_has_Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido_has_Produto` (
  `Pedido_idPedido` INT NOT NULL COMMENT 'ID Pedido',
  `Pedido_Cliente_idCliente` INT NOT NULL COMMENT 'ID Cliente',
  `Produto_idProduto` INT NOT NULL COMMENT 'ID Produto',
  `Qtde` INT NULL COMMENT 'Qtde',
  `Rastreio` VARCHAR(45) NULL COMMENT 'Rastreio',
  PRIMARY KEY (`Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Produto_idProduto`),
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Terceiros_Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Terceiros_Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Terceiros_Vendedor` (
  `idTerceiros_Vendedor` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Terceiros ',
  `Razao Social` VARCHAR(45) NOT NULL COMMENT 'Razao Social ',
  `CNPJ` BIGINT(14) NOT NULL,
  `Local` VARCHAR(80) NOT NULL,
  `Endereço` VARCHAR(80) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  `Tipo_Pessoa` TINYINT NOT NULL DEFAULT 1 COMMENT 'Tipo pessoa - 1-PJ/2-PF',
  PRIMARY KEY (`idTerceiros_Vendedor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CNPJ_UNIQUE` ON `mydb`.`Terceiros_Vendedor` (`CNPJ` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Produto_has_Terceiros_Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Produto_has_Terceiros_Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_has_Terceiros_Vendedor` (
  `Produto_idProduto` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Produto',
  `Terceiros_Vendedor_idTerceiros_Vendedor` INT NOT NULL COMMENT 'Id Vendedor',
  `Qtde` INT NOT NULL DEFAULT 0 COMMENT 'Qtde',
  PRIMARY KEY (`Produto_idProduto`, `Terceiros_Vendedor_idTerceiros_Vendedor`),
  CONSTRAINT `fk_Produto_has_Terceiros-Vendedor_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Terceiros-Vendedor_Terceiros-Vendedor1`
    FOREIGN KEY (`Terceiros_Vendedor_idTerceiros_Vendedor`)
    REFERENCES `mydb`.`Terceiros_Vendedor` (`idTerceiros_Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamentos` (
  `idPagamentos` INT NOT NULL AUTO_INCREMENT COMMENT 'Id pagamento',
  `Tipo` INT NULL DEFAULT 1 COMMENT 'Tipo pagamento - 1-Cartao/2-Boleto/3-Debito/4-Pix/5-Deposito/6-Transferencia',
  `Numero_Cartao` VARCHAR(45) NULL COMMENT 'Numero do cartao',
  `Nome_Cartao` VARCHAR(45) NULL COMMENT 'Nome Titular cartao',
  `Vencimento` DATE NULL COMMENT 'Vencimento ',
  `Ativo` TINYINT NULL COMMENT 'Status - 1-Ativo/2-Inativo',
  `Descricao` VARCHAR(45) NULL COMMENT 'Descricao',
  `Apelido` VARCHAR(45) NULL,
  `Data_Registro` DATE NULL,
  `CPF_Titular` BIGINT NULL COMMENT 'CPF titular',
  PRIMARY KEY (`idPagamentos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente_has_Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente_has_Pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente_has_Pagamentos` (
  `Cliente_idCliente` INT NOT NULL COMMENT 'Id Cliente ',
  `Pagamentos_idPagamentos` INT NOT NULL COMMENT 'Id pagamentos ',
  PRIMARY KEY (`Cliente_idCliente`, `Pagamentos_idPagamentos`),
  CONSTRAINT `fk_Cliente_has_Pagamentos_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Pagamentos_Pagamentos1`
    FOREIGN KEY (`Pagamentos_idPagamentos`)
    REFERENCES `mydb`.`Pagamentos` (`idPagamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Pagamentos_has_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pagamentos_has_Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamentos_has_Pedido` (
  `Pagamentos_idPagamentos` INT NOT NULL COMMENT 'Id pagamentos ',
  `Pedido_idPedido` INT NOT NULL COMMENT 'Id pedidos ',
  `Pedido_Cliente_idCliente` INT NOT NULL COMMENT 'ID Cliente ',
  `Ativo` TINYINT NULL COMMENT 'Status - 1-Pago/2-Em aberto/3-Cancelado/4-Estornado',
  `Pagamentos_has_Pedidocol` VARCHAR(45) NULL,
  PRIMARY KEY (`Pagamentos_idPagamentos`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  CONSTRAINT `fk_Pagamentos_has_Pedido_Pagamentos1`
    FOREIGN KEY (`Pagamentos_idPagamentos`)
    REFERENCES `mydb`.`Pagamentos` (`idPagamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamentos_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
