-- MySQL Script generated by MySQL Workbench
-- Wed Jan 15 16:30:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Identificacao` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  `Tipo Pessoa` TINYINT GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cliente_has_Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente_has_Pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente_has_Pagamentos` (
  `Cliente_idCliente` INT NOT NULL,
  `Pagamentos_idPagamentos` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Pagamentos_idPagamentos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Estoque` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pagamentos` (
  `idPagamentos` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Numero Cartao` VARCHAR(45) NULL,
  `Nome Cartao` VARCHAR(45) NULL,
  `Vencimento` VARCHAR(45) NULL,
  `Status` TINYINT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Apelido` VARCHAR(45) NULL,
  `Data Registro` DATE NULL,
  `CPF Titular` INT NULL,
  PRIMARY KEY (`idPagamentos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pagamentos_has_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagamentos_has_Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pagamentos_has_Pedido` (
  `Pagamentos_idPagamentos` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Status` TINYINT NULL,
  PRIMARY KEY (`Pagamentos_idPagamentos`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pedido` (
  `idPedido` INT NOT NULL,
  `Status` TINYINT NULL,
  `Descrição` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Frete` FLOAT NULL,
  `Entrega` VARCHAR(45) NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pedido_has_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido_has_Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pedido_has_Produto` (
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Qtde` INT NULL,
  `Rastreio` VARCHAR(45) NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Produto_idProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto` (
  `idProduto` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto_has_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto_has_Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto_has_Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto_has_Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto_has_Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto_has_Fornecedor` (
  `Produto_idProduto` INT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Fornecedor_idFornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto_has_Terceiros-Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto_has_Terceiros-Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto_has_Terceiros-Vendedor` (
  `Produto_idProduto` INT NOT NULL,
  `Terceiros-Vendedor_idTerceiros-Vendedor` INT NOT NULL,
  `Qtde` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Terceiros-Vendedor_idTerceiros-Vendedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Terceiros-Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Terceiros-Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Terceiros-Vendedor` (
  `idTerceiros-Vendedor` INT NOT NULL,
  `Razao Social` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceiros-Vendedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
