-- MySQL Script generated by MySQL Workbench
-- Wed Jan 15 20:41:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT COMMENT 'Id - PK e AI.',
  `Nome` VARCHAR(45) NOT NULL,
  `CPF-CNPJ` INT(14) NOT NULL COMMENT 'CPF - CNPJ - controle de tipo 11 ou 14 caractes via App.\nMaximo digitos 14.',
  `Endereço` VARCHAR(80) NULL,
  `Tipo Pessoa` TINYINT GENERATED ALWAYS AS (1) VIRTUAL COMMENT 'Tipo pessoa - 0-PF/1-PJ',
  `Status` TINYINT NOT NULL DEFAULT 1 COMMENT 'Status - 1-Ativo/0-Inativo',
  `Obs` VARCHAR(80) NULL COMMENT 'Obs- campo texto livre',
  `Aniversátio` DATE NOT NULL COMMENT 'Data aniversário',
  `Inclusao` DATE NOT NULL COMMENT 'Data inclusão',
  PRIMARY KEY (`idCliente`, `CPF-CNPJ`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idCliente_UNIQUE` ON `Cliente` (`idCliente` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CPF-CNPJ_UNIQUE` ON `Cliente` (`CPF-CNPJ` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cliente_has_Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente_has_Pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente_has_Pagamentos` (
  `Cliente_idCliente` INT NOT NULL,
  `Pagamentos_idPagamentos` INT NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Pagamentos_idPagamentos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Estoque` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagamentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pagamentos` (
  `idPagamentos` INT NOT NULL COMMENT 'Id pagamento',
  `Tipo` INT NULL DEFAULT 1 COMMENT 'Tipo pagamento - 1-Cartao/2-Boleto/3-Debito/4-Pix/5-Deposito/6-Transferencia',
  `Numero Cartao` VARCHAR(45) NULL COMMENT 'Numero do cartao',
  `Nome Cartao` VARCHAR(45) NULL COMMENT 'Nome Titular cartao',
  `Vencimento` DATE NULL COMMENT 'Vencimento ',
  `Status` TINYINT NULL COMMENT 'Status - 1-Ativo/2-Inativo',
  `Descricao` VARCHAR(45) NULL COMMENT 'Descricao',
  `Apelido` VARCHAR(45) NULL,
  `Data Registro` DATE NULL,
  `CPF Titular` INT NULL COMMENT 'CPF titular',
  PRIMARY KEY (`idPagamentos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pagamentos_has_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagamentos_has_Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pagamentos_has_Pedido` (
  `Pagamentos_idPagamentos` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Status` TINYINT NULL,
  PRIMARY KEY (`Pagamentos_idPagamentos`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT COMMENT 'Numer pedido',
  `Status` TINYINT NOT NULL COMMENT 'Status - 1-Ativo/2-Finalizado/3-Cancelado/4-Devoluçao/5-Em Entrega',
  `Descrição` VARCHAR(45) NULL COMMENT 'Descricao - obs',
  `Cliente_idCliente` INT NOT NULL COMMENT 'ID Cliente',
  `Frete` FLOAT NOT NULL COMMENT 'Frete valor',
  `LocalEntrega` VARCHAR(45) NOT NULL COMMENT 'Local entrega',
  PRIMARY KEY (`idPedido`, `Status`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idPedido_UNIQUE` ON `Pedido` (`idPedido` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pedido_has_Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido_has_Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pedido_has_Produto` (
  `Pedido_idPedido` INT NOT NULL AUTO_INCREMENT,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `Qtde` INT NULL,
  `Rastreio` VARCHAR(45) NULL,
  PRIMARY KEY (`Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Produto_idProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT COMMENT 'ID - codigo produto',
  `Nome` VARCHAR(45) NOT NULL COMMENT 'Nome - descriçlão ',
  `Categoria` VARCHAR(45) NOT NULL DEFAULT 0 COMMENT 'Categoria - tipo produto',
  `Valor` FLOAT NOT NULL COMMENT 'Valor ',
  `Nota` FLOAT NULL DEFAULT 0 COMMENT 'Nota produto',
  `Peso` FLOAT NOT NULL DEFAULT 0 COMMENT 'Pseo produto',
  `Volume` FLOAT NOT NULL DEFAULT 0 COMMENT 'Volume produto',
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idProduto_UNIQUE` ON `Produto` (`idProduto` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto_has_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto_has_Estoque` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto_has_Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto_has_Fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto_has_Fornecedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto_has_Fornecedor` (
  `Produto_idProduto` INT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Fornecedor_idFornecedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto_has_Terceiros-Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto_has_Terceiros-Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto_has_Terceiros-Vendedor` (
  `Produto_idProduto` INT NOT NULL,
  `Terceiros-Vendedor_idTerceiros-Vendedor` INT NOT NULL,
  `Qtde` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Terceiros-Vendedor_idTerceiros-Vendedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Terceiros-Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Terceiros-Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Terceiros-Vendedor` (
  `idTerceiros-Vendedor` INT NOT NULL,
  `Razao Social` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  `Endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceiros-Vendedor`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
