-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 15:26:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliemtes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliemtes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliemtes` (
  `idCliemtes` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Clientes ',
  `CPF` BIGINT(11) NOT NULL COMMENT 'CPF',
  `NomeCompleto` VARCHAR(45) NOT NULL COMMENT 'Nome Completo',
  `Endereco` VARCHAR(80) NOT NULL COMMENT 'Endereço',
  `Obs` VARCHAR(255) NULL COMMENT 'Obs.',
  `Aniversario` DATE NULL COMMENT 'Aniversaro cliente ',
  `Ativo` TINYINT NOT NULL COMMENT 'Ativo 1-Ativo/0-Inativo',
  PRIMARY KEY (`idCliemtes`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `CPF_UNIQUE` ON `mydb`.`Cliemtes` (`CPF` ASC) VISIBLE;

CREATE UNIQUE INDEX `idCliemtes_UNIQUE` ON `mydb`.`Cliemtes` (`idCliemtes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Veiculos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Veiculos` (
  `idVeiculos` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Veiculos',
  `Cliemtes_idCliemtes` INT NOT NULL COMMENT 'Id Clientes ',
  `Marca` VARCHAR(45) NOT NULL COMMENT 'Marca carro',
  `Modelo` VARCHAR(45) NOT NULL COMMENT 'Modelo Carro',
  `Ano` YEAR(4) NOT NULL COMMENT 'Ano Carro',
  `Cor` VARCHAR(45) NOT NULL COMMENT 'Cor carro',
  `Placa` VARCHAR(4) NOT NULL COMMENT 'Placa carro ',
  `Chassi` VARCHAR(45) NOT NULL COMMENT 'Chassi carro',
  `Ativo` VARCHAR(45) NOT NULL COMMENT 'Ativo - 1-Ativo/0-Inativo',
  `Datarevisao` DATE NULL COMMENT 'Data revisao',
  `DataConserto` DATE NULL COMMENT 'Data conserto',
  PRIMARY KEY (`idVeiculos`, `Cliemtes_idCliemtes`),
  CONSTRAINT `fk_Veiculos_Cliemtes`
    FOREIGN KEY (`Cliemtes_idCliemtes`)
    REFERENCES `mydb`.`Cliemtes` (`idCliemtes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Veiculos_Cliemtes_idx` ON `mydb`.`Veiculos` (`Cliemtes_idCliemtes` ASC) VISIBLE;

CREATE UNIQUE INDEX `idVeiculos_UNIQUE` ON `mydb`.`Veiculos` (`idVeiculos` ASC) VISIBLE;

CREATE UNIQUE INDEX `Placa_UNIQUE` ON `mydb`.`Veiculos` (`Placa` ASC) VISIBLE;

CREATE UNIQUE INDEX `Chassi_UNIQUE` ON `mydb`.`Veiculos` (`Chassi` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mecanicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mecanicos` (
  `idMecanicos` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Mecanicos ',
  `Nome` VARCHAR(45) NOT NULL COMMENT 'Nome',
  `Matricula` VARCHAR(45) NOT NULL COMMENT 'Matricula RH',
  `Admissao` DATETIME NOT NULL COMMENT 'Admissao',
  `Nascimento` DATE NOT NULL COMMENT 'Data Nascimento',
  PRIMARY KEY (`idMecanicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Equipe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Equipe ',
  `Mecanicos_idMecanicos` INT NOT NULL COMMENT 'Id Mecanicos ',
  PRIMARY KEY (`idEquipe`, `Mecanicos_idMecanicos`),
  CONSTRAINT `fk_Equipe_Mecanicos1`
    FOREIGN KEY (`Mecanicos_idMecanicos`)
    REFERENCES `mydb`.`Mecanicos` (`idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Equipe_Mecanicos1_idx` ON `mydb`.`Equipe` (`Mecanicos_idMecanicos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OS` (
  `idOS` INT NOT NULL AUTO_INCREMENT COMMENT 'Id OS ',
  `DataOS` DATE NOT NULL COMMENT 'Data OS',
  `Entrega` DATE NOT NULL COMMENT 'Entrega ',
  `Ativo` TINYINT NOT NULL COMMENT 'Ativo 1-Ativo/0-Inativo',
  `TipoConserto` VARCHAR(45) NOT NULL COMMENT 'Tipo conserto ',
  `Dataprevista` DATE NOT NULL COMMENT 'Data prevista',
  `Equipe_idEquipe` INT NOT NULL COMMENT 'Id Equipe Avaliacao',
  `Equipe_Mecanicos_idMecanicos` INT NOT NULL COMMENT 'Id Equipe Mecanicos Manutencao',
  PRIMARY KEY (`idOS`, `Equipe_idEquipe`, `Equipe_Mecanicos_idMecanicos`),
  CONSTRAINT `fk_OS_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe` , `Equipe_Mecanicos_idMecanicos`)
    REFERENCES `mydb`.`Equipe` (`idEquipe` , `Mecanicos_idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_OS_Equipe1_idx` ON `mydb`.`OS` (`Equipe_idEquipe` ASC, `Equipe_Mecanicos_idMecanicos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pecas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pecas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pecas` (
  `idPecas` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Peças ',
  `Descricao` VARCHAR(45) NOT NULL COMMENT 'Descricao',
  `Partnumber` VARCHAR(45) NOT NULL COMMENT 'PartNumber',
  PRIMARY KEY (`idPecas`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPecas_UNIQUE` ON `mydb`.`Pecas` (`idPecas` ASC) VISIBLE;

CREATE UNIQUE INDEX `Partnumber_UNIQUE` ON `mydb`.`Pecas` (`Partnumber` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Estoque',
  `Local` VARCHAR(45) NOT NULL COMMENT 'Local',
  `Obs` VARCHAR(45) NOT NULL COMMENT 'Obs',
  `Qtde` INT NOT NULL COMMENT 'Qtde em estoque ',
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEstoque_UNIQUE` ON `mydb`.`Estoque` (`idEstoque` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Servicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servicos` (
  `idServicos` INT NOT NULL AUTO_INCREMENT COMMENT 'Is Serviços ',
  `Descricao` VARCHAR(45) NOT NULL COMMENT 'Descrição',
  `Valor` FLOAT NOT NULL COMMENT 'Valor',
  `Obs` VARCHAR(255) NULL COMMENT 'Obs',
  PRIMARY KEY (`idServicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculos_has_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Veiculos_has_OS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Veiculos_has_OS` (
  `Veiculos_idVeiculos` INT NOT NULL COMMENT 'Id Veicullos',
  `Veiculos_Cliemtes_idCliemtes` INT NOT NULL COMMENT 'Id Clientes ',
  `OS_idOS` INT NOT NULL COMMENT 'Id OS',
  PRIMARY KEY (`Veiculos_idVeiculos`, `Veiculos_Cliemtes_idCliemtes`, `OS_idOS`),
  CONSTRAINT `fk_Veiculos_has_OS_Veiculos1`
    FOREIGN KEY (`Veiculos_idVeiculos` , `Veiculos_Cliemtes_idCliemtes`)
    REFERENCES `mydb`.`Veiculos` (`idVeiculos` , `Cliemtes_idCliemtes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculos_has_OS_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Veiculos_has_OS_OS1_idx` ON `mydb`.`Veiculos_has_OS` (`OS_idOS` ASC) VISIBLE;

CREATE INDEX `fk_Veiculos_has_OS_Veiculos1_idx` ON `mydb`.`Veiculos_has_OS` (`Veiculos_idVeiculos` ASC, `Veiculos_Cliemtes_idCliemtes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Servicos_has_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Servicos_has_OS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servicos_has_OS` (
  `IdServicohasOS` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Servicso has OS',
  `Servicos_idServicos` INT NOT NULL COMMENT 'Id Serviços',
  `OS_idOS` INT NOT NULL COMMENT 'Id OS',
  `QtdeServico` INT NOT NULL COMMENT 'Qtde Serviço',
  `Total` FLOAT NOT NULL COMMENT 'Valor Total Serviços',
  PRIMARY KEY (`IdServicohasOS`, `Servicos_idServicos`, `OS_idOS`),
  CONSTRAINT `fk_Serviços_has_OS_Serviços1`
    FOREIGN KEY (`Servicos_idServicos`)
    REFERENCES `mydb`.`Servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serviços_has_OS_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Serviços_has_OS_OS1_idx` ON `mydb`.`Servicos_has_OS` (`OS_idOS` ASC) VISIBLE;

CREATE INDEX `fk_Serviços_has_OS_Serviços1_idx` ON `mydb`.`Servicos_has_OS` (`Servicos_idServicos` ASC) VISIBLE;

CREATE UNIQUE INDEX `IdServicohasOS_UNIQUE` ON `mydb`.`Servicos_has_OS` (`IdServicohasOS` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pecas_has_OS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pecas_has_OS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pecas_has_OS` (
  `IdPecashasOs` INT NOT NULL AUTO_INCREMENT COMMENT 'ID Pecas has OS',
  `Pecas_idPecas` INT NOT NULL COMMENT 'Id Pecas',
  `OS_idOS` INT NOT NULL COMMENT 'Id OS',
  `QtdePecas` INT NOT NULL COMMENT 'Qtde Pecas',
  `Total` FLOAT NOT NULL COMMENT 'Valor Total',
  PRIMARY KEY (`IdPecashasOs`, `Pecas_idPecas`, `OS_idOS`),
  CONSTRAINT `fk_Pecas_has_OS_Pecas1`
    FOREIGN KEY (`Pecas_idPecas`)
    REFERENCES `mydb`.`Pecas` (`idPecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pecas_has_OS_OS1`
    FOREIGN KEY (`OS_idOS`)
    REFERENCES `mydb`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pecas_has_OS_OS1_idx` ON `mydb`.`Pecas_has_OS` (`OS_idOS` ASC) VISIBLE;

CREATE INDEX `fk_Pecas_has_OS_Pecas1_idx` ON `mydb`.`Pecas_has_OS` (`Pecas_idPecas` ASC) VISIBLE;

CREATE UNIQUE INDEX `IdPecas_has_Os_UNIQUE` ON `mydb`.`Pecas_has_OS` (`IdPecashasOs` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Pecas_has_Estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pecas_has_Estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pecas_has_Estoque` (
  `Pecas_idPecas` INT NOT NULL COMMENT 'Id Peças ',
  `Estoque_idEstoque` INT NOT NULL COMMENT 'Id Estoque',
  PRIMARY KEY (`Pecas_idPecas`, `Estoque_idEstoque`),
  CONSTRAINT `fk_Pecas_has_Estoque_Pecas1`
    FOREIGN KEY (`Pecas_idPecas`)
    REFERENCES `mydb`.`Pecas` (`idPecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pecas_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pecas_has_Estoque_Estoque1_idx` ON `mydb`.`Pecas_has_Estoque` (`Estoque_idEstoque` ASC) VISIBLE;

CREATE INDEX `fk_Pecas_has_Estoque_Pecas1_idx` ON `mydb`.`Pecas_has_Estoque` (`Pecas_idPecas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Especialidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Especialidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Especialidades` (
  `idEspecialidades` INT NOT NULL AUTO_INCREMENT COMMENT 'Id Especialidades',
  `Descricao` VARCHAR(45) NULL COMMENT 'Descricao',
  PRIMARY KEY (`idEspecialidades`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEspecialidades_UNIQUE` ON `mydb`.`Especialidades` (`idEspecialidades` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanicos_has_Especialidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mecanicos_has_Especialidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mecanicos_has_Especialidades` (
  `Mecanicos_idMecanicos` INT NOT NULL COMMENT 'Id Mecanicos ',
  `Especialidades_idEspecialidades` INT NOT NULL COMMENT 'Id Especialidades',
  PRIMARY KEY (`Mecanicos_idMecanicos`, `Especialidades_idEspecialidades`),
  CONSTRAINT `fk_Mecanicos_has_Especialidades_Mecanicos1`
    FOREIGN KEY (`Mecanicos_idMecanicos`)
    REFERENCES `mydb`.`Mecanicos` (`idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanicos_has_Especialidades_Especialidades1`
    FOREIGN KEY (`Especialidades_idEspecialidades`)
    REFERENCES `mydb`.`Especialidades` (`idEspecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mecanicos_has_Especialidades_Especialidades1_idx` ON `mydb`.`Mecanicos_has_Especialidades` (`Especialidades_idEspecialidades` ASC) VISIBLE;

CREATE INDEX `fk_Mecanicos_has_Especialidades_Mecanicos1_idx` ON `mydb`.`Mecanicos_has_Especialidades` (`Mecanicos_idMecanicos` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
